https://datasets.imdbws.com/name.basics.tsv.gz

---


https://datasets.imdbws.com/title.akas.tsv.gz

---


https://datasets.imdbws.com/title.basics.tsv.gz

---


https://datasets.imdbws.com/title.crew.tsv.gz

---


https://datasets.imdbws.com/title.episode.tsv.gz

---


https://datasets.imdbws.com/title.principals.tsv.gz

---


https://datasets.imdbws.com/title.ratings.tsv.gz

In [1]:
### Import du dataset TITLE.AKAS via la méthode 'chunksize' -- on scinde en 3 le dataset source (48.635.537 lignes au total donc chunksize = 16.300.000)  =========================>
import pandas as pd

#param_nrows = 1000000
param_nrows = None
sample_nrows = 1000000


# Charger les données
#name_basics = pd.read_csv('https://datasets.imdbws.com/name.basics.tsv.gz', sep='\t',compression='gzip', na_values=["\\N"], low_memory=True,nrows=param_nrows)
title_akas = pd.read_csv('https://datasets.imdbws.com/title.akas.tsv.gz', sep='\t',compression='gzip', na_values=["\\N"], low_memory=True,nrows=param_nrows, chunksize=16300000)
#title_basics = pd.read_csv('https://datasets.imdbws.com/title.basics.tsv.gz', sep='\t', na_values=["\\N"], low_memory=True,nrows=param_nrows)
#title_crews = pd.read_csv('https://datasets.imdbws.com/title.crew.tsv.gz', sep='\t',compression='gzip', na_values=["\\N"], low_memory=True,nrows=param_nrows)
#title_episode = pd.read_csv('https://datasets.imdbws.com/title.episode.tsv.gz', sep='\t',compression='gzip', na_values=["\\N"], low_memory=True,nrows=param_nrows)
#title_principals = pd.read_csv('https://datasets.imdbws.com/title.principals.tsv.gz', sep='\t',compression='gzip', na_values=["\\N"], low_memory=True,nrows=param_nrows)
#title_ratings = pd.read_csv('https://datasets.imdbws.com/title.ratings.tsv.gz', sep='\t',compression='gzip', na_values=["\\N"], low_memory=True,nrows=param_nrows)

##**------ EXPLORATION DATASET title_akas ------------------------------->**

In [ ]:
#### subset issu du chunksize = 16.300.000 de l'import du dataset source title_akas (1/3) ==========================>
df_title_akas_part1 = next(title_akas)
display(df_title_akas_part1)

<ipython-input-3-269914b7459c>:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_title_akas_part1 = next(title_akas)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Carmencita,NaN,NaN,original,NaN,1
1,tt0000001,2,Carmencita,DE,NaN,NaN,literal title,0
2,tt0000001,3,Carmencita,US,NaN,imdbDisplay,NaN,0
3,tt0000001,4,Carmencita - spanyol tánc,HU,NaN,imdbDisplay,NaN,0
4,tt0000001,5,Καρμενσίτα,GR,NaN,imdbDisplay,NaN,0
...,...,...,...,...,...,...,...,...
16299995,tt14684848,6,Folge #1.352,DE,de,NaN,NaN,0
16299996,tt14684848,7,エピソード #1.352,JP,ja,NaN,NaN,0
16299997,tt14684848,8,Episodio #1.352,ES,es,NaN,NaN,0
16299998,tt1468485,1,Episode #1.10296,NaN,NaN,original,NaN,1
16299999,tt1468485,2,Episódio #1.10296,PT,pt,NaN,NaN,0

In [ ]:
#### subset issu du chunksize = 16.300.000 de l'import du dataset source title_akas (2/3) ==========================>
df_title_akas_part2 = next(title_akas)
display(df_title_akas_part2)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
16300000,tt1468485,3,एपिसोड #1.10296,IN,hi,NaN,NaN,0
16300001,tt1468485,4,Épisode #1.10296,FR,fr,NaN,NaN,0
16300002,tt1468485,5,Episodio #1.10296,IT,it,NaN,NaN,0
16300003,tt1468485,6,Folge #1.10296,DE,de,NaN,NaN,0
16300004,tt1468485,7,エピソード #1.10296,JP,ja,NaN,NaN,0
...,...,...,...,...,...,...,...,...
32599995,tt29307222,2,Episódio #1.6576,PT,pt,NaN,NaN,0
32599996,tt29307222,3,एपिसोड #1.6576,IN,hi,NaN,NaN,0
32599997,tt29307222,4,Épisode #1.6576,FR,fr,NaN,NaN,0
32599998,tt29307222,5,Episodio #1.6576,IT,it,NaN,NaN,0
32599999,tt29307222,6,Folge #1.6576,DE,de,NaN,NaN,0

In [ ]:
#### subset issu du chunksize = 16.300.000 de l'import du dataset source title_akas (3/3) ==========================>
df_title_akas_part3 = next(title_akas)
display(df_title_akas_part3)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
32600000,tt29307222,7,エピソード #1.6576,JP,ja,NaN,NaN,0
32600001,tt29307222,8,Episodio #1.6576,ES,es,NaN,NaN,0
32600002,tt29307223,1,Episode #1.6575,NaN,NaN,original,NaN,1
32600003,tt29307223,2,Episódio #1.6575,PT,pt,NaN,NaN,0
32600004,tt29307223,3,एपिसोड #1.6575,IN,hi,NaN,NaN,0
...,...,...,...,...,...,...,...,...
48657464,tt9916852,7,エピソード #3.20,JP,ja,NaN,NaN,0
48657465,tt9916852,8,Episodio #3.20,ES,es,NaN,NaN,0
48657466,tt9916856,1,The Wind,NaN,NaN,original,NaN,1
48657467,tt9916856,2,The Wind,DE,NaN,imdbDisplay,NaN,0
48657468,tt9916880,1,Horrid Henry Knows It All,NaN,NaN,original,NaN,1

In [ ]:
### Caractéristiques générales dataset title_akas ===> scindé en 3 part = [df_title_akas_part1, df_title_akas_part2, df_title_akas_part3]
df_title_akas_part1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16300000 entries, 0 to 16299999
Data columns (total 8 columns):
 #   Column           Dtype
---  ------           -----
 0   titleId          object
 1   ordering         int64
 2   title            object
 3   region           object
 4   language         object
 5   types            object
 6   attributes       object
 7   isOriginalTitle  int64
dtypes: int64(2), object(6)
memory usage: 994.9+ MB

In [ ]:
## identification doublons / unicité des valeurs de chaque colonne => part 1 - part 2 - part 3
print(f"Format dataset 'df_title_akass_' => Part1: {df_title_akas_part1.shape} || Part2: {df_title_akas_part2.shape} || Part3: {df_title_akas_part3.shape}")
print(f"Nb val uniques dans col. 'titleId' => Part1: {df_title_akas_part1['titleId'].nunique()} || Part2: {df_title_akas_part2['titleId'].nunique()} || Part3: {df_title_akas_part3['titleId'].nunique()}")
print(f"Nb val uniques dans col. 'ordering' => Part1: {df_title_akas_part1['ordering'].nunique()} || Part2: {df_title_akas_part2['ordering'].nunique()} || Part3: {df_title_akas_part3['ordering'].nunique()}")
print(f"Nb val uniques dans col. 'title' => Part1: {df_title_akas_part1['title'].nunique()} || Part2: {df_title_akas_part2['title'].nunique()} || Part3: {df_title_akas_part3['title'].nunique()}")
print(f"Nb val uniques dans col. 'region' => Part1: {df_title_akas_part1['region'].nunique()} || Part2: {df_title_akas_part2['region'].nunique()} || Part3: {df_title_akas_part3['region'].nunique()}")
print(f"Nb val uniques dans col. 'language' => Part1: {df_title_akas_part1['language'].nunique()} || Part2: {df_title_akas_part2['language'].nunique()} || Part3: {df_title_akas_part3['language'].nunique()}")
print(f"Nb val uniques dans col. 'types' => Part1: {df_title_akas_part1['types'].nunique()} || Part2: {df_title_akas_part2['types'].nunique()} || Part3: {df_title_akas_part3['types'].nunique()}")
print(f"Nb val uniques dans col. 'attributes' => Part1: {df_title_akas_part1['attributes'].nunique()} || Part2: {df_title_akas_part2['attributes'].nunique()} || || Part3: {df_title_akas_part3['attributes'].nunique()}")
print(f"Nb val uniques dans col. 'isOriginalTitle' => Part1: {df_title_akas_part1['isOriginalTitle'].nunique()} || Part2: {df_title_akas_part2['isOriginalTitle'].nunique()} || Part3: {df_title_akas_part3['isOriginalTitle'].nunique()}")

Format dataset 'df_title_akass_' => Part1: (16300000, 8) || Part2: (16300000, 8) || Part3: (16035537, 8)
Nb val uniques dans col. 'titleId' => Part1: 3523051 || Part2: 3520588 || Part3: 3790237
Nb val uniques dans col. 'ordering' => Part1: 251 || Part2: 161 || Part3: 117
Nb val uniques dans col. 'title' => Part1: 3261533 || Part2: 2226214 || Part3: 2592392
Nb val uniques dans col. 'region' => Part1: 233 || Part2: 238 || Part3: 238
Nb val uniques dans col. 'language' => Part1: 92 || Part2: 98 || Part3: 83
Nb val uniques dans col. 'types' => Part1: 23 || Part2: 17 || Part3: 13
Nb val uniques dans col. 'attributes' => Part1: 182 || Part2: 115 || || Part3: 112
Nb val uniques dans col. 'isOriginalTitle' => Part1: 2 || Part2: 2 || Part3: 2

In [ ]:
### zoom 'ordering' ==========>
print(df_title_akas_part1['ordering'].idxmax())
display(df_title_akas_part1.iloc[df_title_akas_part1['ordering'].idxmax(),:])
#display(df_title_akas_part1.loc[df_title_akas_part1['titleId']=='tt0088814'])
df_title_akas_part1.loc[df_title_akas_part1['titleId']=='tt0088814',['titleId','title','region','language','attributes']].groupby('attributes')[['titleId','title','region','language']].value_counts()

772854

titleId                     tt0088814
ordering                          251
title              The Black Cauldron
region                             US
language                           en
types                             NaN
attributes                        NaN
isOriginalTitle                     0
Name: 772854, dtype: object

attributes                   titleId    title                         region  language
alternative transliteration  tt0088814  Taran to kuroi mahō no kama   JP      ja          1
informal alternative title   tt0088814  O Caldeirão Mágico            MZ      pt          1
                                        Tarón y el caldero mágico     XSA     es          1
                                        タラン と くろい まほう の かま            JP      ja          1
informal literal title       tt0088814  Le Chaudron noir              DZ      fr          1
                                                                      MA      fr          1
                                                                      SN      fr          1
                                                                      TN      fr          1
                                        O Caldeirão Negro             MZ      pt          1
                                        Le Chaudron noir              LB      fr          1
                                                                      CM      fr          1
                                                                      CG      fr          1
                                        De Zwarte Ketel               BE      nl          1
                                                                      NL      nl          1
                                        Den svarta kitteln            FI      sv          1
                                        Der schwarze Kessel           CH      de          1
                                        El caldero negro              PH      es          1
                                                                      US      es          1
                                                                      XSA     es          1
                                                                      XWW     es          1
                                        Kaldron Hitam                 ID      id          1
                                                                      MY      ms          1
                                                                      SG      ms          1
                                        La caldera negra              ES      ca          1
                                        Le Chaudron noir              BE      fr          1
                                                                      BJ      fr          1
                                                                      CA      fr          1
reissue title                tt0088814  Црни казан                    XYU     hr          1
                                                                              sr          1
transliterated title         tt0088814  Chérniyat Kazán               BG      bg          1
                                        Chórnyĭ kotyól                SUHH    ru          1
                                        Cȓni kàzan                    XYU     hr          1
                                                                              sr          1
                                        Cȓni kòtao                    XYU     hr          1
                                                                              sr          1
                                        Hēi-shén-guō-chuán-qí         CN      cmn         1
                                                                      HK      cmn         1
                                                                      MY      cmn         1
                                                                      SG      cmn         1
                                        Korudoron                     JP      ja          1
                                        Taran to kuroi mahou no kama  JP      ja          1
Name: count, dtype: int64

In [ ]:
### zoom language ===============>
print(df_title_akas_part1['language'].value_counts().head(10))
print(df_title_akas_part2['language'].value_counts().head(10))
print(df_title_akas_part3['language'].value_counts().head(10))

language
ja    1444040
fr    1425593
hi    1396468
es    1381620
de    1381612
it    1380576
pt    1380506
en     266652
ru      31539
tr      23251
Name: count, dtype: int64
language
ja     1651412
fr     1635275
hi     1634760
es     1624111
de     1623991
it     1623559
pt     1623539
en      134049
cmn       9842
tr        5939
Name: count, dtype: int64
language
ja     1536970
fr     1517155
hi     1514468
es     1504730
de     1504444
it     1504100
pt     1504029
en      138395
cmn      11385
tr        8269
Name: count, dtype: int64

In [ ]:
### zoom region ===============>
print(df_title_akas_part1['region'].value_counts().head(10))
print(df_title_akas_part2['region'].value_counts().head(10))
print(df_title_akas_part3['region'].value_counts().head(10))

region
FR    1518776
DE    1500065
JP    1497160
ES    1479817
IN    1464691
IT    1464386
PT    1425326
US     656952
GB     216239
CA     124952
Name: count, dtype: int64
region
DE    1690116
JP    1688689
IN    1678517
FR    1674258
ES    1655701
IT    1654031
PT    1632181
US     376963
GB     120140
CA      68789
Name: count, dtype: int64
region
JP    1590724
DE    1581152
FR    1567151
IN    1563107
ES    1540995
IT    1538707
PT    1514477
US     499658
GB     151257
CA      77837
Name: count, dtype: int64

In [ ]:
### % de NaN pour chaque colonne => part 1
print(f"% NaN pour la colonne 'titleId' => {round(df_title_akas_part1['titleId'].isna().sum()/len(df_title_akas_part1['titleId'])*100,3)}%")
print(f"% NaN pour la colonne 'ordering' => {round(df_title_akas_part1['ordering'].isna().sum()/len(df_title_akas_part1['ordering'])*100,2)}%")
print(f"% NaN pour la colonne 'title' => {round(df_title_akas_part1['title'].isna().sum()/len(df_title_akas_part1['title'])*100,2)}%")
print(f"% NaN pour la colonne 'region' => {round(df_title_akas_part1['region'].isna().sum()/len(df_title_akas_part1['region'])*100,2)}%")
print(f"% NaN pour la colonne 'language' => {round(df_title_akas_part1['language'].isna().sum()/len(df_title_akas_part1['language'])*100,2)}%")
print(f"% NaN pour la colonne 'types' => {round(df_title_akas_part1['types'].isna().sum()/len(df_title_akas_part1['types'])*100,2)}%")
print(f"% NaN pour la colonne 'attributes' => {round(df_title_akas_part1['attributes'].isna().sum()/len(df_title_akas_part1['attributes'])*100,2)}%")
print(f"% NaN pour la colonne 'isOriginalTitle' => {round(df_title_akas_part1['isOriginalTitle'].isna().sum()/len(df_title_akas_part1['isOriginalTitle'])*100,2)}%")

% NaN pour la colonne 'titleId' => 0.0%
% NaN pour la colonne 'ordering' => 0.0%
% NaN pour la colonne 'title' => 0.0%
% NaN pour la colonne 'region' => 21.86%
% NaN pour la colonne 'language' => 37.42%
% NaN pour la colonne 'types' => 65.14%
% NaN pour la colonne 'attributes' => 98.92%
% NaN pour la colonne 'isOriginalTitle' => 0.0%

In [ ]:
### % de NaN pour chaque colonne => part 2
print(f"% NaN pour la colonne 'titleId' => {round(df_title_akas_part2['titleId'].isna().sum()/len(df_title_akas_part2['titleId'])*100,3)}%")
print(f"% NaN pour la colonne 'ordering' => {round(df_title_akas_part2['ordering'].isna().sum()/len(df_title_akas_part2['ordering'])*100,2)}%")
print(f"% NaN pour la colonne 'title' => {round(df_title_akas_part2['title'].isna().sum()/len(df_title_akas_part2['title'])*100,2)}%")
print(f"% NaN pour la colonne 'region' => {round(df_title_akas_part2['region'].isna().sum()/len(df_title_akas_part2['region'])*100,2)}%")
print(f"% NaN pour la colonne 'language' => {round(df_title_akas_part2['language'].isna().sum()/len(df_title_akas_part2['language'])*100,2)}%")
print(f"% NaN pour la colonne 'types' => {round(df_title_akas_part2['types'].isna().sum()/len(df_title_akas_part2['types'])*100,2)}%")
print(f"% NaN pour la colonne 'attributes' => {round(df_title_akas_part2['attributes'].isna().sum()/len(df_title_akas_part2['attributes'])*100,2)}%")
print(f"% NaN pour la colonne 'isOriginalTitle' => {round(df_title_akas_part2['isOriginalTitle'].isna().sum()/len(df_title_akas_part2['isOriginalTitle'])*100,2)}%")

% NaN pour la colonne 'titleId' => 0.0%
% NaN pour la colonne 'ordering' => 0.0%
% NaN pour la colonne 'title' => 0.0%
% NaN pour la colonne 'region' => 21.67%
% NaN pour la colonne 'language' => 28.95%
% NaN pour la colonne 'types' => 73.17%
% NaN pour la colonne 'attributes' => 99.72%
% NaN pour la colonne 'isOriginalTitle' => 0.0%

In [ ]:
### % de NaN pour chaque colonne => part 3
print(f"% NaN pour la colonne 'titleId' => {round(df_title_akas_part3['titleId'].isna().sum()/len(df_title_akas_part3['titleId'])*100,3)}%")
print(f"% NaN pour la colonne 'ordering' => {round(df_title_akas_part3['ordering'].isna().sum()/len(df_title_akas_part3['ordering'])*100,2)}%")
print(f"% NaN pour la colonne 'title' => {round(df_title_akas_part3['title'].isna().sum()/len(df_title_akas_part3['title'])*100,2)}%")
print(f"% NaN pour la colonne 'region' => {round(df_title_akas_part3['region'].isna().sum()/len(df_title_akas_part3['region'])*100,2)}%")
print(f"% NaN pour la colonne 'language' => {round(df_title_akas_part3['language'].isna().sum()/len(df_title_akas_part3['language'])*100,2)}%")
print(f"% NaN pour la colonne 'types' => {round(df_title_akas_part3['types'].isna().sum()/len(df_title_akas_part3['types'])*100,2)}%")
print(f"% NaN pour la colonne 'attributes' => {round(df_title_akas_part3['attributes'].isna().sum()/len(df_title_akas_part3['attributes'])*100,2)}%")
print(f"% NaN pour la colonne 'isOriginalTitle' => {round(df_title_akas_part3['isOriginalTitle'].isna().sum()/len(df_title_akas_part3['isOriginalTitle'])*100,2)}%")

% NaN pour la colonne 'titleId' => 0.0%
% NaN pour la colonne 'ordering' => 0.0%
% NaN pour la colonne 'title' => 0.0%
% NaN pour la colonne 'region' => 23.81%
% NaN pour la colonne 'language' => 32.88%
% NaN pour la colonne 'types' => 69.43%
% NaN pour la colonne 'attributes' => 99.63%
% NaN pour la colonne 'isOriginalTitle' => 0.0%

In [ ]:
### Nombre de lignes avec grand nombre valeurs NaN =======> part 1 ==> concl. pas de résultat significatif
print(f"Nombre de lignes qui contiennent 8 valeurs NaN = {(df_title_akas_part1.isna().sum(axis=1)==8).sum()} lignes soit {round(100*(df_title_akas_part1.isna().sum(axis=1)==8).sum()/len(df_title_akas_part1),2)}%") ### lignes à supprimer !
print(f"Nombre de lignes qui contiennent 7 valeurs NaN = {(df_title_akas_part1.isna().sum(axis=1)==7).sum()} lignes soit {round(100*(df_title_akas_part1.isna().sum(axis=1)==7).sum()/len(df_title_akas_part1),2)}%") ### lignes à supprimer ?
print(f"Nombre de lignes qui contiennent 6 valeurs NaN = {(df_title_akas_part1.isna().sum(axis=1)==6).sum()} lignes soit {round(100*(df_title_akas_part1.isna().sum(axis=1)==6).sum()/len(df_title_akas_part1),2)}%")
print(f"Nombre de lignes qui contiennent 5 valeurs NaN = {(df_title_akas_part1.isna().sum(axis=1)==5).sum()} lignes soit {round(100*(df_title_akas_part1.isna().sum(axis=1)==5).sum()/len(df_title_akas_part1),2)}%")
print(f"Nombre de lignes qui contiennent 4 valeurs NaN = {(df_title_akas_part1.isna().sum(axis=1)==4).sum()} lignes soit {round(100*(df_title_akas_part1.isna().sum(axis=1)==4).sum()/len(df_title_akas_part1),2)}%")
print(f"Nombre de lignes qui ne contiennent aucune valeurs NaN = {(df_title_akas_part1.isna().sum(axis=1)==0).sum()} lignes soit {round((df_title_akas_part1.isna().sum(axis=1)==0).sum()/len(df_title_akas_part1),2)}%")

Nombre de lignes qui contiennent 8 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 7 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 6 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 5 valeurs NaN = 2 lignes soit 0.0%
Nombre de lignes qui contiennent 4 valeurs NaN = 30759 lignes soit 0.19%
Nombre de lignes qui ne contiennent aucune valeurs NaN = 223 lignes soit 0.0%

In [ ]:
### Nombre de lignes avec grand nombre valeurs NaN =======> part 2  ==> concl. pas de résultat significatif
print(f"Nombre de lignes qui contiennent 8 valeurs NaN = {(df_title_akas_part2.isna().sum(axis=1)==8).sum()} lignes soit {round(100*(df_title_akas_part2.isna().sum(axis=1)==8).sum()/len(df_title_akas_part2),2)}%") ### lignes à supprimer !
print(f"Nombre de lignes qui contiennent 7 valeurs NaN = {(df_title_akas_part2.isna().sum(axis=1)==7).sum()} lignes soit {round(100*(df_title_akas_part2.isna().sum(axis=1)==7).sum()/len(df_title_akas_part2),2)}%") ### lignes à supprimer ?
print(f"Nombre de lignes qui contiennent 6 valeurs NaN = {(df_title_akas_part2.isna().sum(axis=1)==6).sum()} lignes soit {round(100*(df_title_akas_part2.isna().sum(axis=1)==6).sum()/len(df_title_akas_part2),2)}%")
print(f"Nombre de lignes qui contiennent 5 valeurs NaN = {(df_title_akas_part2.isna().sum(axis=1)==5).sum()} lignes soit {round(100*(df_title_akas_part2.isna().sum(axis=1)==5).sum()/len(df_title_akas_part2),2)}%")
print(f"Nombre de lignes qui contiennent 4 valeurs NaN = {(df_title_akas_part2.isna().sum(axis=1)==4).sum()} lignes soit {round(100*(df_title_akas_part2.isna().sum(axis=1)==4).sum()/len(df_title_akas_part2),2)}%")
print(f"Nombre de lignes qui ne contiennent aucune valeurs NaN = {(df_title_akas_part2.isna().sum(axis=1)==0).sum()} lignes soit {round((df_title_akas_part2.isna().sum(axis=1)==0).sum()/len(df_title_akas_part2),2)}%")

Nombre de lignes qui contiennent 8 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 7 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 6 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 5 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 4 valeurs NaN = 5984 lignes soit 0.04%
Nombre de lignes qui ne contiennent aucune valeurs NaN = 81 lignes soit 0.0%

In [ ]:
### Nombre de lignes avec grand nombre valeurs NaN =======> part 3  ==> concl. pas de résultat significatif
print(f"Nombre de lignes qui contiennent 8 valeurs NaN = {(df_title_akas_part3.isna().sum(axis=1)==8).sum()} lignes soit {round(100*(df_title_akas_part3.isna().sum(axis=1)==8).sum()/len(df_title_akas_part3),2)}%") ### lignes à supprimer !
print(f"Nombre de lignes qui contiennent 7 valeurs NaN = {(df_title_akas_part3.isna().sum(axis=1)==7).sum()} lignes soit {round(100*(df_title_akas_part3.isna().sum(axis=1)==7).sum()/len(df_title_akas_part3),2)}%") ### lignes à supprimer ?
print(f"Nombre de lignes qui contiennent 6 valeurs NaN = {(df_title_akas_part3.isna().sum(axis=1)==6).sum()} lignes soit {round(100*(df_title_akas_part3.isna().sum(axis=1)==6).sum()/len(df_title_akas_part3),2)}%")
print(f"Nombre de lignes qui contiennent 5 valeurs NaN = {(df_title_akas_part3.isna().sum(axis=1)==5).sum()} lignes soit {round(100*(df_title_akas_part3.isna().sum(axis=1)==5).sum()/len(df_title_akas_part3),2)}%")
print(f"Nombre de lignes qui contiennent 4 valeurs NaN = {(df_title_akas_part3.isna().sum(axis=1)==4).sum()} lignes soit {round(100*(df_title_akas_part3.isna().sum(axis=1)==4).sum()/len(df_title_akas_part3),2)}%")
print(f"Nombre de lignes qui ne contiennent aucune valeurs NaN = {(df_title_akas_part3.isna().sum(axis=1)==0).sum()} lignes soit {round((df_title_akas_part3.isna().sum(axis=1)==0).sum()/len(df_title_akas_part3),2)}%")

Nombre de lignes qui contiennent 8 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 7 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 6 valeurs NaN = 0 lignes soit 0.0%
Nombre de lignes qui contiennent 5 valeurs NaN = 1 lignes soit 0.0%
Nombre de lignes qui contiennent 4 valeurs NaN = 11974 lignes soit 0.07%
Nombre de lignes qui ne contiennent aucune valeurs NaN = 132 lignes soit 0.0%

In [ ]:
### ZOOM colonne 'isOriginaltitle' Nombre de lignes 'isOriginalTitle' == 1 ======================> 10.833.864 valeurs au total (qui correspond au nombre total de films dans les autres tables)
print(len(df_title_akas_part1.loc[df_title_akas_part1['isOriginalTitle']==1]))
print(len(df_title_akas_part2.loc[df_title_akas_part2['isOriginalTitle']==1]))
print(len(df_title_akas_part3.loc[df_title_akas_part3['isOriginalTitle']==1]))
print(f"Total valeur isOriginalTitle == 1 : {len(df_title_akas_part1.loc[df_title_akas_part1['isOriginalTitle']==1])+len(df_title_akas_part2.loc[df_title_akas_part2['isOriginalTitle']==1])+len(df_title_akas_part3.loc[df_title_akas_part3['isOriginalTitle']==1])}")

3523048
3520587
3790229
Total valeur isOriginalTitle == 1 : 10833864

In [ ]:
### ZOOM colonne 'attributs' ==============================>
print("df_title_akas_part1 =======>")
print(df_title_akas_part1['attributes'].value_counts().head(20))
print("\n\ndf_title_akas_part2 =======>")
print(df_title_akas_part2['attributes'].value_counts().head(20))
print("\n\ndf_title_akas_part3 =======>")
print(df_title_akas_part3['attributes'].value_counts().head(20))

df_title_akas_part1 =======>
attributes
transliterated title           25888
alternative spelling           11735
video box title                11171
literal title                  10634
new title                       9670
complete title                  9222
literal English title           7966
reissue title                   7606
series title                    5802
short title                     5525
DVD box title                   4989
alternative transliteration     4811
original subtitled version      4353
informal literal title          4280
dubbed version                  4088
poster title                    4080
informal title                  3958
informal English title          3430
cable TV title                  3130
long title                      2460
Name: count, dtype: int64


df_title_akas_part2 =======>
attributes
alternative spelling           4623
complete title                 3219
literal English title          3215
new title                      3051
alternative transliteration    2727
short title                    2383
series title                   2239
transliterated title           1910
reissue title                  1872
DVD box title                  1573
literal title                  1563
informal English title         1409
informal title                 1256
informal alternative title     1232
original script title          1127
dubbed version                 1076
long title                     1034
informal short title            809
subtitle                        672
second season title             616
Name: count, dtype: int64


df_title_akas_part3 =======>
attributes
new title                      5950
literal English title          5742
alternative spelling           5263
complete title                 4095
alternative transliteration    3043
short title                    2996
subtitle                       2979
video catalogue title          2387
reissue title                  1934
informal English title         1930
series title                   1925
DVD box title                  1723
literal title                  1698
transliterated title           1647
informal title                 1310
dubbed version                 1258
long title                     1047
original subtitled version     1000
informal alternative title      962
informal short title            725
Name: count, dtype: int64

In [ ]:
### ZOOM valeurs non vide pour colonne 'attributes'  ====>

mask_attributes_na = df_title_akas_part1['attributes'].isna()
df_title_akas_part1[~mask_attributes_na]
mask_attributes_litEng = df_title_akas_part1['attributes']=='literal English title'
df_title_akas_part1[mask_attributes_litEng]
mask_attributes_VOST = df_title_akas_part1['attributes']=='original subtitled version'
df_title_akas_part1[mask_attributes_VOST]

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
1679,tt0000417,25,El viaje a la luna,UY,NaN,NaN,original subtitled version,0
9379,tt0003102,8,Pero el amor mío no muere,AR,NaN,NaN,original subtitled version,0
15177,tt0004972,15,El nacimiento de una nación,UY,NaN,NaN,original subtitled version,0
15304,tt0005005,2,La moneda rota,AR,NaN,NaN,original subtitled version,0
21167,tt0006864,15,Intolerancia,UY,NaN,NaN,original subtitled version,0
...,...,...,...,...,...,...,...,...
16150564,tt14623808,3,How to hack your boss,US,NaN,NaN,original subtitled version,0
16151634,tt14624330,6,Family Game,CA,en,NaN,original subtitled version,0
16197529,tt1464335,38,Uncharted: Fuera del mapa,UY,NaN,NaN,original subtitled version,0
16202508,tt1464540,22,Soy el número cuatro,UY,NaN,NaN,original subtitled version,0
16295560,tt1468322,9,Hottrake no shima,JP,NaN,NaN,original subtitled version,0

# **-----------------------------Nettoyage---------------------------**

In [1]:
import pandas as pd

# Parameters
param_nrows = None  # Set to None to load all rows, or specify a number for a subset
chunksize = 16300000

# Initialize an empty list to hold processed chunks
chunks = []

# Process the dataset in chunks
for chunk in pd.read_csv('https://datasets.imdbws.com/title.akas.tsv.gz', sep='\t', compression='gzip', na_values=["\\N"], low_memory=True, nrows=param_nrows, chunksize=chunksize):
    # Fill missing values in the language column with the values from the region column
    chunk['language'].fillna(chunk['region'], inplace=True)
    # Convert the 'language' column to lowercase
    chunk['language'] = chunk['language'].str.lower()
    # Filter the rows where 'isOriginal' is 1 or 'language' is 'fr'
    filtered_chunk = chunk[(chunk['isOriginalTitle'] == 1) | (chunk['language'] == 'fr')]
    # Drop the columns 'types' and 'attributes'
    filtered_chunk.drop(columns=['types', 'attributes'], inplace=True)
    # Append the filtered chunk to the list
    chunks.append(filtered_chunk)

# Concatenate all filtered chunks into a single DataFrame
title_akas_cleaned = pd.concat(chunks, ignore_index=True)

# Verify the changes
print(title_akas_cleaned.info())
display(title_akas_cleaned.head())

<ipython-input-1-5a6f0b3a52da>:11: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('https://datasets.imdbws.com/title.akas.tsv.gz', sep='\t', compression='gzip', na_values=["\\N"], low_memory=True, nrows=param_nrows, chunksize=chunksize):
<ipython-input-1-5a6f0b3a52da>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_chunk.drop(columns=['types', 'attributes'], inplace=True)
<ipython-input-1-5a6f0b3a52da>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_chunk.drop(columns=['types', 'attributes'], inplace=True)
<ipython-input-1-5a6f0b3a52da>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_chunk.drop(columns=['types', 'attributes'], inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15694874 entries, 0 to 15694873
Data columns (total 6 columns):
 #   Column           Dtype
---  ------           -----
 0   titleId          object
 1   ordering         int64
 2   title            object
 3   region           object
 4   language         object
 5   isOriginalTitle  int64
dtypes: int64(2), object(4)
memory usage: 718.5+ MB
None

,titleId,ordering,title,region,language,isOriginalTitle
0,tt0000001,1,Carmencita,NaN,NaN,1
1,tt0000002,1,Le clown et ses chiens,NaN,NaN,1
2,tt0000002,5,Le clown et ses chiens,FR,fr,0
3,tt0000003,1,Pauvre Pierrot,NaN,NaN,1
4,tt0000003,3,Pauvre Pierrot,FR,fr,0

In [2]:
# Save the cleaned DataFrame to a CSV file
title_akas_cleaned.to_csv('title_akas_cleaned.csv', index=False)

# Verify the changes
print(title_akas_cleaned.info())
display(title_akas_cleaned.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15694874 entries, 0 to 15694873
Data columns (total 6 columns):
 #   Column           Dtype
---  ------           -----
 0   titleId          object
 1   ordering         int64
 2   title            object
 3   region           object
 4   language         object
 5   isOriginalTitle  int64
dtypes: int64(2), object(4)
memory usage: 718.5+ MB
None

,titleId,ordering,title,region,language,isOriginalTitle
0,tt0000001,1,Carmencita,NaN,NaN,1
1,tt0000002,1,Le clown et ses chiens,NaN,NaN,1
2,tt0000002,5,Le clown et ses chiens,FR,fr,0
3,tt0000003,1,Pauvre Pierrot,NaN,NaN,1
4,tt0000003,3,Pauvre Pierrot,FR,fr,0